### ISSUE TITLE
Example request: HTTP POST

### ISSUE THREAD

**Issue by linonetwo** [apepkuss/wasmedge-rust-examples#1]
Can I send http request using `reqwest` package? So I can use https://github.com/valentinegb/openai crate, which uses `reqwest` package.

I'm planning to switch from extism to wasmedge, because extism have poor support for HTTP request, and debug experience and test coverage are poor.

**Comment by linonetwo** [comment]
I guess this is the example https://wasmedge.org/book/en/write_wasm/rust/networking.html#an-http-client-example

**Comment by apepkuss** [comment]
@linonetwo Could you please tell us the purpose of what you're doing? For adding a new example in this repo, or building up your own app? If you'd like to build an app, we recommend you open a new issue at [WasmEdge issues](https://github.com/WasmEdge/WasmEdge/issues).

**Comment by linonetwo** [comment]
This

> building up your own app

Thanks, I'm just new to wasmedge, and I'm looking at examples to make sure it can do what I want.

Now that I found the example in the doc, I'm certain now.

**Comment by apepkuss** [comment]
Great!
