### ISSUE TITLE
Cannot run examples

### ISSUE THREAD

**Issue by neliusdelange** [apepkuss/wasmedge-rust-examples#3]
Hi there,

I am attempting to run a simple Rust SDK example, but getting the error:

error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_PluginLoadFromPath` in module `ffi`
  --> /home/neliusdelange/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmedge-sys-0.13.0/src/plugin.rs:40:23
   |
40 |         unsafe { ffi::WasmEdge_PluginLoadFromPath(c_path.as_ptr()) }
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `ffi`

Please assist.

Thank you
Nelius

**Comment by neliusdelange** [comment]
Hi again, 
The above behavior seems to be applicable in WSL2 (Ubuntu on Windows). 
Running the same code in a standard Ubuntu installation works.

Thanks,
Nelius

**Comment by apepkuss** [comment]
@neliusdelange Thanks for your report. According to the error message, the wasmedge library is not of `v0.12.0`. You can try the following two commands in your terminal program to check if `wasmedge-v0.12.0` has been deployed on your local system correctly or not:

```bash
# check the version
wasmedge --version

# check if you're using the correct wasmedge runtime 
# when multiple versions exist in the environment
which wasmedge
```

Let us know if any other issues. Thanks a lot!
